#	Copyright(c) 2018 Gluwa, Inc.
#
#	This file is part of Creditcoin.
#
#	Creditcoin is free software: you can redistribute it and/or modify
#	it under the terms of the GNU Lesser General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#	
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU Lesser General Public License for more details.
#	
#	You should have received a copy of the GNU Lesser General Public License
#	along with Creditcoin. If not, see <https://www.gnu.org/licenses/>.

#       This docker-compose file uses the following images below:
#
#       REPOSITORY                         TAG              IMAGE ID       SIZE
#       gluwa/creditcoin-client-priv      testing-1.8-01   c7bc1e69897c   718MB

#       Built from:
#       Creditcoin-Client, https://github.com/gluwa/Creditcoin-Client/tree/dev:
#            - dev@f36b61f3edd3a344ae7ff6f2fff0cb8e3641fa6a, using cccore/ccplugin v1.1.2


version: "3.7"

services:
  client:
    network_mode: "host"
    image: gluwa/creditcoin-client-priv:testing-1.8-01
    container_name: creditcoin-client-testnet
    tty: true
    stdin_open: true
    secrets:
     - source: client_config
       target: /home/Creditcoin/Client/appsettings.json

secrets:
  client_config:
    file: ./clientConfig.json

